source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'hack pop' do
	pod 'Flurry-iOS-SDK/FlurrySDK' #Analytics Pod
end

target 'hack popTests' do
	pod 'Flurry-iOS-SDK/FlurrySDK' #Analytics Pod
end

target 'hack popUITests' do
	pod 'Flurry-iOS-SDK/FlurrySDK' #Analytics Pod
end

